name: Security vulnerability
description: Report a vulnerability on any versions of the tool
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: What versions is this vulnerability observed on?
    validations:
      required: true
