name: Submit dependencies
on: push
jobs:
  library:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: .scripts/dependency_report_generate.sh -m library -c allSourceSetsCompileDependenciesMetadata -o dependencies_library_raw
      - run: echo "SCANNED_AT=$(TZ=UTC date +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
