name: Submit dependencies
on: push
jobs:
  library:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          gradle-build-module: :library
          gradle-build-configuration: allSourceSetsCompileDependenciesMetadata
          fail-on-error: true
